version: "3.8"
services:
  client:
    build:
      context: ./client
    container_name: blog_frontend
    ports:
      - "3000:80"
    depends_on:
      - server
  server:
    build:
      context: ./server
    container_name: blog_api
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=devops_blog
      - PGPORT=5432
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: devops_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devops_blog
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
